- name: Extract important firmware strings
  run: |
    echo "========== PRODUCT =========="
    strings "Archer_C54(US)_V1_230608.bin" | grep -i archer || true

    echo "========== TP-LINK =========="
    strings "Archer_C54(US)_V1_230608.bin" | grep -i tplink || true

    echo "========== BOARD =========="
    strings "Archer_C54(US)_V1_230608.bin" | grep -i board || true

    echo "========== HW =========="
    strings "Archer_C54(US)_V1_230608.bin" | grep -i hw || true

    echo "========== MODEL =========="
    strings "Archer_C54(US)_V1_230608.bin" | grep -i c54 || true
